version: '3'

services:
  psp_server:
    container_name: 'psp_server'
    image: node:10-alpine
    command: npm run start
    working_dir: /usr/local/app/
    depends_on: 
      - psp_database
    volumes: 
      - './:/usr/local/app'
    ports: 
      - '9020:9020'
    networks: 
      - pagarme
    environment: 
      - MYSQL_URL=psp_database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=psp

  psp_database:
    container_name: 'psp_database'
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - '9021:3306'
    volumes: 
      - 'psp_mysql_data:/var/lib/mysql'
    networks: 
      - pagarme
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=psp

volumes:
  psp_mysql_data:

networks: 
  pagarme:
    external:
      name: pagarme