version: '3'

services:
  psp_server:
    container_name: 'psp_server'
    image: node:10-alpine
    command: npm run start:dev
    working_dir: /usr/local/app/
    depends_on:
      - psp_database
    volumes:
      - './:/usr/local/app'
    ports:
      - '9020:9020'
    networks:
      - pagarme
    environment:
      - MYSQL_URL=mysql://root:root@psp_database:3306/psp
      - MYSQL_DB_NAME=psp

  psp_server_test:
    image: node:10-alpine
    command: npm run test
    working_dir: /usr/local/app/
    restart: on-failure
    container_name: psp_server_test
    volumes:
      - './:/usr/local/app/'
    ports:
      - '3000:3000'
    depends_on:
      - psp_database_test
    networks:
      - pagarme
    environment:
      - MYSQL_URL=mysql://root:root@psp_database_test:3306/psp
      - MYSQL_DB_NAME=psp

  psp_database:
    container_name: 'psp_database'
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '9021:3306'
    volumes:
      - 'psp_mysql_data:/var/lib/mysql'
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pagarme
    environment:
      - MYSQL_ROOT_PASSWORD=root

  psp_database_test:
    container_name: 'psp_database_test'
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    volumes:
      - 'psp_mysql_test_data:/var/lib/mysql'
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pagarme
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  psp_mysql_data:
  psp_mysql_test_data:

networks:
  pagarme:
    external:
      name: pagarme
